version: 2

builds:
  - main: ./cmd/operator
    binary: orb-operator
    env:
      - CGO_ENABLED=0
      - GOFLAGS={{ if index .Env "GO_BUILD_FLAGS" }}{{ .Env.GO_BUILD_FLAGS }}{{ end }}
    goos:
      - linux
    goarch:
      - amd64
      - arm64

dockers_v2:
  - images:
      - "{{ .Env.IMAGE_REPO }}"
    tags:
      - "{{ .Env.IMAGE_TAG }}"
    platforms:
      - linux/amd64
      - linux/arm64
    dockerfile: Dockerfile

release:
  disable: '{{ ne .Env.ENABLE_RELEASE_PIPELINE "true" }}'
  extra_files:
    - glob: _output/install.json
  header: |
    ## Install

    ```bash
    kubectl apply -f https://github.com/joelanford/orb-operator/releases/download/{{ .Tag }}/install.json
    ```

changelog:
  disable: '{{ ne .Env.ENABLE_RELEASE_PIPELINE "true" }}'
