version: 2

builds:
  - main: ./cmd/operator
    binary: orb-operator
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64

dockers_v2:
  - images:
      - ghcr.io/joelanford/orb-operator
    tags:
      - "{{ .Tag }}"
    platforms:
      - linux/amd64
      - linux/arm64
    dockerfile: Dockerfile

release:
  disable: true

snapshot:
  version_template: "{{ .ShortCommit }}"

changelog:
  disable: true
