// Code generated by controller-gen. DO NOT EDIT.

package applyconfigurations

import (
	v1alpha1 "github.com/joelanford/orb-operator/api/v1alpha1"
	apiv1alpha1 "github.com/joelanford/orb-operator/applyconfigurations/api/v1alpha1"
	internal "github.com/joelanford/orb-operator/applyconfigurations/internal"
	runtime "k8s.io/apimachinery/pkg/runtime"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	managedfields "k8s.io/apimachinery/pkg/util/managedfields"
)

// ForKind returns an apply configuration type for the given GroupVersionKind, or nil if no
// apply configuration type exists for the given GroupVersionKind.
func ForKind(kind schema.GroupVersionKind) interface{} {
	switch kind {
	// Group=orb.operatorframework.io, Version=v1alpha1
	case v1alpha1.SchemeGroupVersion.WithKind("Assertion"):
		return &apiv1alpha1.AssertionApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("CELExpressionAssertion"):
		return &apiv1alpha1.CELExpressionAssertionApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("ClusterObjectDeployment"):
		return &apiv1alpha1.ClusterObjectDeploymentApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("ClusterObjectDeploymentSpec"):
		return &apiv1alpha1.ClusterObjectDeploymentSpecApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("ClusterObjectDeploymentStatus"):
		return &apiv1alpha1.ClusterObjectDeploymentStatusApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("ClusterObjectDeploymentTemplate"):
		return &apiv1alpha1.ClusterObjectDeploymentTemplateApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("ClusterObjectDeploymentTemplateMetadata"):
		return &apiv1alpha1.ClusterObjectDeploymentTemplateMetadataApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("ClusterObjectDeploymentTemplateSpec"):
		return &apiv1alpha1.ClusterObjectDeploymentTemplateSpecApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("ClusterObjectSetRevision"):
		return &apiv1alpha1.ClusterObjectSetRevisionApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("ClusterObjectSetRevisionSpec"):
		return &apiv1alpha1.ClusterObjectSetRevisionSpecApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("ClusterObjectSetRevisionStatus"):
		return &apiv1alpha1.ClusterObjectSetRevisionStatusApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("ClusterObjectSetRevisionStatusSummary"):
		return &apiv1alpha1.ClusterObjectSetRevisionStatusSummaryApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("ClusterObjectSlice"):
		return &apiv1alpha1.ClusterObjectSliceApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("ConditionEqualAssertion"):
		return &apiv1alpha1.ConditionEqualAssertionApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("FieldsEqualAssertion"):
		return &apiv1alpha1.FieldsEqualAssertionApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("FieldValueAssertion"):
		return &apiv1alpha1.FieldValueAssertionApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("ObjectStatus"):
		return &apiv1alpha1.ObjectStatusApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("ObservedPhase"):
		return &apiv1alpha1.ObservedPhaseApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("Phase"):
		return &apiv1alpha1.PhaseApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("PhaseObject"):
		return &apiv1alpha1.PhaseObjectApplyConfiguration{}

	}
	return nil
}

func NewTypeConverter(scheme *runtime.Scheme) managedfields.TypeConverter {
	return managedfields.NewSchemeTypeConverter(scheme, internal.Parser())
}
