// Package v1alpha1 contains API types for the orb-operator extension object management system.
// +groupName=orb.operatorframework.io
package v1alpha1

//go:generate go tool controller-gen crd output:crd:dir=../../deploy/crds paths=./...
//go:generate go tool controller-gen object paths=./...
