//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Assertion) DeepCopyInto(out *Assertion) {
	*out = *in
	if in.ConditionEqual != nil {
		in, out := &in.ConditionEqual, &out.ConditionEqual
		*out = new(ConditionEqualAssertion)
		**out = **in
	}
	if in.FieldsEqual != nil {
		in, out := &in.FieldsEqual, &out.FieldsEqual
		*out = new(FieldsEqualAssertion)
		**out = **in
	}
	if in.FieldValue != nil {
		in, out := &in.FieldValue, &out.FieldValue
		*out = new(FieldValueAssertion)
		**out = **in
	}
	if in.CELExpression != nil {
		in, out := &in.CELExpression, &out.CELExpression
		*out = new(CELExpressionAssertion)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Assertion.
func (in *Assertion) DeepCopy() *Assertion {
	if in == nil {
		return nil
	}
	out := new(Assertion)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CELExpressionAssertion) DeepCopyInto(out *CELExpressionAssertion) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CELExpressionAssertion.
func (in *CELExpressionAssertion) DeepCopy() *CELExpressionAssertion {
	if in == nil {
		return nil
	}
	out := new(CELExpressionAssertion)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterObjectDeployment) DeepCopyInto(out *ClusterObjectDeployment) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterObjectDeployment.
func (in *ClusterObjectDeployment) DeepCopy() *ClusterObjectDeployment {
	if in == nil {
		return nil
	}
	out := new(ClusterObjectDeployment)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ClusterObjectDeployment) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterObjectDeploymentList) DeepCopyInto(out *ClusterObjectDeploymentList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ClusterObjectDeployment, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterObjectDeploymentList.
func (in *ClusterObjectDeploymentList) DeepCopy() *ClusterObjectDeploymentList {
	if in == nil {
		return nil
	}
	out := new(ClusterObjectDeploymentList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ClusterObjectDeploymentList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterObjectDeploymentSpec) DeepCopyInto(out *ClusterObjectDeploymentSpec) {
	*out = *in
	if in.RevisionHistoryLimit != nil {
		in, out := &in.RevisionHistoryLimit, &out.RevisionHistoryLimit
		*out = new(int32)
		**out = **in
	}
	if in.ProgressDeadlineMinutes != nil {
		in, out := &in.ProgressDeadlineMinutes, &out.ProgressDeadlineMinutes
		*out = new(int32)
		**out = **in
	}
	in.Template.DeepCopyInto(&out.Template)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterObjectDeploymentSpec.
func (in *ClusterObjectDeploymentSpec) DeepCopy() *ClusterObjectDeploymentSpec {
	if in == nil {
		return nil
	}
	out := new(ClusterObjectDeploymentSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterObjectDeploymentStatus) DeepCopyInto(out *ClusterObjectDeploymentStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ActiveRevisions != nil {
		in, out := &in.ActiveRevisions, &out.ActiveRevisions
		*out = make([]ClusterObjectSetStatusSummary, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterObjectDeploymentStatus.
func (in *ClusterObjectDeploymentStatus) DeepCopy() *ClusterObjectDeploymentStatus {
	if in == nil {
		return nil
	}
	out := new(ClusterObjectDeploymentStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterObjectDeploymentTemplate) DeepCopyInto(out *ClusterObjectDeploymentTemplate) {
	*out = *in
	in.Metadata.DeepCopyInto(&out.Metadata)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterObjectDeploymentTemplate.
func (in *ClusterObjectDeploymentTemplate) DeepCopy() *ClusterObjectDeploymentTemplate {
	if in == nil {
		return nil
	}
	out := new(ClusterObjectDeploymentTemplate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterObjectDeploymentTemplateMetadata) DeepCopyInto(out *ClusterObjectDeploymentTemplateMetadata) {
	*out = *in
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Annotations != nil {
		in, out := &in.Annotations, &out.Annotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterObjectDeploymentTemplateMetadata.
func (in *ClusterObjectDeploymentTemplateMetadata) DeepCopy() *ClusterObjectDeploymentTemplateMetadata {
	if in == nil {
		return nil
	}
	out := new(ClusterObjectDeploymentTemplateMetadata)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterObjectDeploymentTemplateSpec) DeepCopyInto(out *ClusterObjectDeploymentTemplateSpec) {
	*out = *in
	if in.CollisionProtection != nil {
		in, out := &in.CollisionProtection, &out.CollisionProtection
		*out = new(CollisionProtection)
		**out = **in
	}
	if in.Phases != nil {
		in, out := &in.Phases, &out.Phases
		*out = make([]Phase, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterObjectDeploymentTemplateSpec.
func (in *ClusterObjectDeploymentTemplateSpec) DeepCopy() *ClusterObjectDeploymentTemplateSpec {
	if in == nil {
		return nil
	}
	out := new(ClusterObjectDeploymentTemplateSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterObjectSet) DeepCopyInto(out *ClusterObjectSet) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterObjectSet.
func (in *ClusterObjectSet) DeepCopy() *ClusterObjectSet {
	if in == nil {
		return nil
	}
	out := new(ClusterObjectSet)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ClusterObjectSet) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterObjectSetList) DeepCopyInto(out *ClusterObjectSetList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ClusterObjectSet, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterObjectSetList.
func (in *ClusterObjectSetList) DeepCopy() *ClusterObjectSetList {
	if in == nil {
		return nil
	}
	out := new(ClusterObjectSetList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ClusterObjectSetList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterObjectSetSpec) DeepCopyInto(out *ClusterObjectSetSpec) {
	*out = *in
	in.ClusterObjectDeploymentTemplateSpec.DeepCopyInto(&out.ClusterObjectDeploymentTemplateSpec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterObjectSetSpec.
func (in *ClusterObjectSetSpec) DeepCopy() *ClusterObjectSetSpec {
	if in == nil {
		return nil
	}
	out := new(ClusterObjectSetSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterObjectSetStatus) DeepCopyInto(out *ClusterObjectSetStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.CompletedAt != nil {
		in, out := &in.CompletedAt, &out.CompletedAt
		*out = (*in).DeepCopy()
	}
	if in.ObservedPhases != nil {
		in, out := &in.ObservedPhases, &out.ObservedPhases
		*out = make([]ObservedPhase, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterObjectSetStatus.
func (in *ClusterObjectSetStatus) DeepCopy() *ClusterObjectSetStatus {
	if in == nil {
		return nil
	}
	out := new(ClusterObjectSetStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterObjectSetStatusSummary) DeepCopyInto(out *ClusterObjectSetStatusSummary) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterObjectSetStatusSummary.
func (in *ClusterObjectSetStatusSummary) DeepCopy() *ClusterObjectSetStatusSummary {
	if in == nil {
		return nil
	}
	out := new(ClusterObjectSetStatusSummary)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterObjectSlice) DeepCopyInto(out *ClusterObjectSlice) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	if in.Objects != nil {
		in, out := &in.Objects, &out.Objects
		*out = make([]SliceObject, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ObjectMap != nil {
		in, out := &in.ObjectMap, &out.ObjectMap
		*out = make(map[ObjectKey][]byte, len(*in))
		for key, val := range *in {
			var outVal []byte
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = make([]byte, len(*in))
				copy(*out, *in)
			}
			(*out)[key] = outVal
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterObjectSlice.
func (in *ClusterObjectSlice) DeepCopy() *ClusterObjectSlice {
	if in == nil {
		return nil
	}
	out := new(ClusterObjectSlice)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ClusterObjectSlice) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterObjectSliceList) DeepCopyInto(out *ClusterObjectSliceList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ClusterObjectSlice, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterObjectSliceList.
func (in *ClusterObjectSliceList) DeepCopy() *ClusterObjectSliceList {
	if in == nil {
		return nil
	}
	out := new(ClusterObjectSliceList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ClusterObjectSliceList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConditionEqualAssertion) DeepCopyInto(out *ConditionEqualAssertion) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConditionEqualAssertion.
func (in *ConditionEqualAssertion) DeepCopy() *ConditionEqualAssertion {
	if in == nil {
		return nil
	}
	out := new(ConditionEqualAssertion)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FieldValueAssertion) DeepCopyInto(out *FieldValueAssertion) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FieldValueAssertion.
func (in *FieldValueAssertion) DeepCopy() *FieldValueAssertion {
	if in == nil {
		return nil
	}
	out := new(FieldValueAssertion)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FieldsEqualAssertion) DeepCopyInto(out *FieldsEqualAssertion) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FieldsEqualAssertion.
func (in *FieldsEqualAssertion) DeepCopy() *FieldsEqualAssertion {
	if in == nil {
		return nil
	}
	out := new(FieldsEqualAssertion)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ObjectCounts) DeepCopyInto(out *ObjectCounts) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ObjectCounts.
func (in *ObjectCounts) DeepCopy() *ObjectCounts {
	if in == nil {
		return nil
	}
	out := new(ObjectCounts)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ObjectKey) DeepCopyInto(out *ObjectKey) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ObjectKey.
func (in *ObjectKey) DeepCopy() *ObjectKey {
	if in == nil {
		return nil
	}
	out := new(ObjectKey)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ObjectRef) DeepCopyInto(out *ObjectRef) {
	*out = *in
	out.ObjectKey = in.ObjectKey
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ObjectRef.
func (in *ObjectRef) DeepCopy() *ObjectRef {
	if in == nil {
		return nil
	}
	out := new(ObjectRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ObjectStatus) DeepCopyInto(out *ObjectStatus) {
	*out = *in
	if in.Messages != nil {
		in, out := &in.Messages, &out.Messages
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ObjectStatus.
func (in *ObjectStatus) DeepCopy() *ObjectStatus {
	if in == nil {
		return nil
	}
	out := new(ObjectStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ObservedPhase) DeepCopyInto(out *ObservedPhase) {
	*out = *in
	if in.CompletedAt != nil {
		in, out := &in.CompletedAt, &out.CompletedAt
		*out = (*in).DeepCopy()
	}
	out.ObjectCounts = in.ObjectCounts
	if in.ObjectDetails != nil {
		in, out := &in.ObjectDetails, &out.ObjectDetails
		*out = make([]ObjectStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ObservedPhase.
func (in *ObservedPhase) DeepCopy() *ObservedPhase {
	if in == nil {
		return nil
	}
	out := new(ObservedPhase)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Phase) DeepCopyInto(out *Phase) {
	*out = *in
	if in.CollisionProtection != nil {
		in, out := &in.CollisionProtection, &out.CollisionProtection
		*out = new(CollisionProtection)
		**out = **in
	}
	if in.Objects != nil {
		in, out := &in.Objects, &out.Objects
		*out = make([]PhaseObject, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Phase.
func (in *Phase) DeepCopy() *Phase {
	if in == nil {
		return nil
	}
	out := new(Phase)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PhaseObject) DeepCopyInto(out *PhaseObject) {
	*out = *in
	in.Object.DeepCopyInto(&out.Object)
	if in.ObjectRef != nil {
		in, out := &in.ObjectRef, &out.ObjectRef
		*out = new(ObjectRef)
		**out = **in
	}
	if in.CollisionProtection != nil {
		in, out := &in.CollisionProtection, &out.CollisionProtection
		*out = new(CollisionProtection)
		**out = **in
	}
	if in.Assertions != nil {
		in, out := &in.Assertions, &out.Assertions
		*out = make([]Assertion, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PhaseObject.
func (in *PhaseObject) DeepCopy() *PhaseObject {
	if in == nil {
		return nil
	}
	out := new(PhaseObject)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SliceObject) DeepCopyInto(out *SliceObject) {
	*out = *in
	out.ObjectKey = in.ObjectKey
	if in.Content != nil {
		in, out := &in.Content, &out.Content
		*out = make([]byte, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SliceObject.
func (in *SliceObject) DeepCopy() *SliceObject {
	if in == nil {
		return nil
	}
	out := new(SliceObject)
	in.DeepCopyInto(out)
	return out
}
