// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

// AssertionApplyConfiguration represents a declarative configuration of the Assertion type for use
// with apply.
//
// Assertion defines a single availability check that must pass before the
// containing object is considered available. Exactly one of conditionEqual,
// fieldsEqual, fieldValue, or celExpression must be set.
type AssertionApplyConfiguration struct {
	// conditionEqual checks that a status condition with the given type has the
	// expected status value.
	ConditionEqual *ConditionEqualAssertionApplyConfiguration `json:"conditionEqual,omitempty"`
	// fieldsEqual checks that two fields on the object have equal values.
	FieldsEqual *FieldsEqualAssertionApplyConfiguration `json:"fieldsEqual,omitempty"`
	// fieldValue checks that a single field on the object matches an expected
	// value.
	FieldValue *FieldValueAssertionApplyConfiguration `json:"fieldValue,omitempty"`
	// celExpression evaluates a CEL expression against the object. The
	// expression must evaluate to true for the assertion to pass.
	CELExpression *CELExpressionAssertionApplyConfiguration `json:"celExpression,omitempty"`
}

// AssertionApplyConfiguration constructs a declarative configuration of the Assertion type for use with
// apply.
func Assertion() *AssertionApplyConfiguration {
	return &AssertionApplyConfiguration{}
}

// WithConditionEqual sets the ConditionEqual field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ConditionEqual field is set to the value of the last call.
func (b *AssertionApplyConfiguration) WithConditionEqual(value *ConditionEqualAssertionApplyConfiguration) *AssertionApplyConfiguration {
	b.ConditionEqual = value
	return b
}

// WithFieldsEqual sets the FieldsEqual field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the FieldsEqual field is set to the value of the last call.
func (b *AssertionApplyConfiguration) WithFieldsEqual(value *FieldsEqualAssertionApplyConfiguration) *AssertionApplyConfiguration {
	b.FieldsEqual = value
	return b
}

// WithFieldValue sets the FieldValue field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the FieldValue field is set to the value of the last call.
func (b *AssertionApplyConfiguration) WithFieldValue(value *FieldValueAssertionApplyConfiguration) *AssertionApplyConfiguration {
	b.FieldValue = value
	return b
}

// WithCELExpression sets the CELExpression field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CELExpression field is set to the value of the last call.
func (b *AssertionApplyConfiguration) WithCELExpression(value *CELExpressionAssertionApplyConfiguration) *AssertionApplyConfiguration {
	b.CELExpression = value
	return b
}
