// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

// CELExpressionAssertionApplyConfiguration represents a declarative configuration of the CELExpressionAssertion type for use
// with apply.
//
// CELExpressionAssertion evaluates a CEL expression against the managed object.
// The expression has access to the full object and must evaluate to a boolean.
type CELExpressionAssertionApplyConfiguration struct {
	// expression is a CEL expression that must evaluate to true for the
	// assertion to pass. The managed object is available as "self" in the
	// expression scope.
	Expression *string `json:"expression,omitempty"`
	// message is an optional human-readable explanation shown when the assertion
	// fails. When omitted, the raw expression text is used in error messages.
	Message *string `json:"message,omitempty"`
}

// CELExpressionAssertionApplyConfiguration constructs a declarative configuration of the CELExpressionAssertion type for use with
// apply.
func CELExpressionAssertion() *CELExpressionAssertionApplyConfiguration {
	return &CELExpressionAssertionApplyConfiguration{}
}

// WithExpression sets the Expression field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Expression field is set to the value of the last call.
func (b *CELExpressionAssertionApplyConfiguration) WithExpression(value string) *CELExpressionAssertionApplyConfiguration {
	b.Expression = &value
	return b
}

// WithMessage sets the Message field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Message field is set to the value of the last call.
func (b *CELExpressionAssertionApplyConfiguration) WithMessage(value string) *CELExpressionAssertionApplyConfiguration {
	b.Message = &value
	return b
}
