// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	apiv1alpha1 "github.com/joelanford/orb-operator/api/v1alpha1"
)

// ClusterObjectSetRevisionSpecApplyConfiguration represents a declarative configuration of the ClusterObjectSetRevisionSpec type for use
// with apply.
//
// ClusterObjectSetRevisionSpec defines the desired state of a
// ClusterObjectSetRevision. All fields except lifecycleState are immutable
// after creation.
type ClusterObjectSetRevisionSpecApplyConfiguration struct {
	// group is a label-safe identifier that links related revisions together.
	// All revisions sharing the same group form an ordered sequence. The value
	// must be at most 52 characters long.
	Group *string `json:"group,omitempty"`
	// revision is the monotonically increasing sequence number within the
	// group. The first revision is 1.
	Revision *uint32 `json:"revision,omitempty"`
	// lifecycleState controls whether this revision is actively reconciling its
	// managed objects. Allowed values are "Active" and "Archived". An Active
	// revision reconciles and reports availability. Transitioning to Archived
	// triggers teardown (deletion) of any objects still owned by this revision;
	// phases are torn down in reverse order. Once a revision is archived, it
	// cannot be unarchived.
	LifecycleState                                        *apiv1alpha1.LifecycleState `json:"lifecycleState,omitempty"`
	ClusterObjectDeploymentTemplateSpecApplyConfiguration `json:",inline"`
}

// ClusterObjectSetRevisionSpecApplyConfiguration constructs a declarative configuration of the ClusterObjectSetRevisionSpec type for use with
// apply.
func ClusterObjectSetRevisionSpec() *ClusterObjectSetRevisionSpecApplyConfiguration {
	return &ClusterObjectSetRevisionSpecApplyConfiguration{}
}

// WithGroup sets the Group field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Group field is set to the value of the last call.
func (b *ClusterObjectSetRevisionSpecApplyConfiguration) WithGroup(value string) *ClusterObjectSetRevisionSpecApplyConfiguration {
	b.Group = &value
	return b
}

// WithRevision sets the Revision field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Revision field is set to the value of the last call.
func (b *ClusterObjectSetRevisionSpecApplyConfiguration) WithRevision(value uint32) *ClusterObjectSetRevisionSpecApplyConfiguration {
	b.Revision = &value
	return b
}

// WithLifecycleState sets the LifecycleState field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the LifecycleState field is set to the value of the last call.
func (b *ClusterObjectSetRevisionSpecApplyConfiguration) WithLifecycleState(value apiv1alpha1.LifecycleState) *ClusterObjectSetRevisionSpecApplyConfiguration {
	b.LifecycleState = &value
	return b
}

// WithCollisionProtection sets the CollisionProtection field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CollisionProtection field is set to the value of the last call.
func (b *ClusterObjectSetRevisionSpecApplyConfiguration) WithCollisionProtection(value apiv1alpha1.CollisionProtection) *ClusterObjectSetRevisionSpecApplyConfiguration {
	b.ClusterObjectDeploymentTemplateSpecApplyConfiguration.CollisionProtection = &value
	return b
}

// WithPhases adds the given value to the Phases field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Phases field.
func (b *ClusterObjectSetRevisionSpecApplyConfiguration) WithPhases(values ...*PhaseApplyConfiguration) *ClusterObjectSetRevisionSpecApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithPhases")
		}
		b.ClusterObjectDeploymentTemplateSpecApplyConfiguration.Phases = append(b.ClusterObjectDeploymentTemplateSpecApplyConfiguration.Phases, *values[i])
	}
	return b
}
