// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/client-go/applyconfigurations/meta/v1"
)

// ClusterObjectDeploymentStatusApplyConfiguration represents a declarative configuration of the ClusterObjectDeploymentStatus type for use
// with apply.
//
// ClusterObjectDeploymentStatus reports the observed state of a ClusterObjectDeployment.
type ClusterObjectDeploymentStatusApplyConfiguration struct {
	// conditions represent the latest available observations of the
	// ClusterObjectDeployment's state. The "Available" condition indicates whether the
	// active revision's managed objects satisfy their assertions.
	Conditions []v1.ConditionApplyConfiguration `json:"conditions,omitempty"`
	// objectCounts reports aggregate object counts from the latest active
	// revision. Nil when no active revision exists.
	ObjectCounts *ObjectCountsApplyConfiguration `json:"objectCounts,omitempty"`
	// activeRevisions holds the currently active (non-archived)
	// ClusterObjectSet resources, including any revision just created
	// but not yet visible in the informer cache.
	ActiveRevisions []ClusterObjectSetStatusSummaryApplyConfiguration `json:"activeRevisions,omitempty"`
}

// ClusterObjectDeploymentStatusApplyConfiguration constructs a declarative configuration of the ClusterObjectDeploymentStatus type for use with
// apply.
func ClusterObjectDeploymentStatus() *ClusterObjectDeploymentStatusApplyConfiguration {
	return &ClusterObjectDeploymentStatusApplyConfiguration{}
}

// WithConditions adds the given value to the Conditions field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Conditions field.
func (b *ClusterObjectDeploymentStatusApplyConfiguration) WithConditions(values ...*v1.ConditionApplyConfiguration) *ClusterObjectDeploymentStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithConditions")
		}
		b.Conditions = append(b.Conditions, *values[i])
	}
	return b
}

// WithObjectCounts sets the ObjectCounts field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ObjectCounts field is set to the value of the last call.
func (b *ClusterObjectDeploymentStatusApplyConfiguration) WithObjectCounts(value *ObjectCountsApplyConfiguration) *ClusterObjectDeploymentStatusApplyConfiguration {
	b.ObjectCounts = value
	return b
}

// WithActiveRevisions adds the given value to the ActiveRevisions field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the ActiveRevisions field.
func (b *ClusterObjectDeploymentStatusApplyConfiguration) WithActiveRevisions(values ...*ClusterObjectSetStatusSummaryApplyConfiguration) *ClusterObjectDeploymentStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithActiveRevisions")
		}
		b.ActiveRevisions = append(b.ActiveRevisions, *values[i])
	}
	return b
}
