// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

// ClusterObjectSetTemplateApplyConfiguration represents a declarative configuration of the ClusterObjectSetTemplate type for use
// with apply.
//
// ClusterObjectSetTemplate defines the template used to stamp out
// ClusterObjectSetRevision resources.
type ClusterObjectSetTemplateApplyConfiguration struct {
	// metadata contains labels and annotations that are propagated to each
	// ClusterObjectSetRevision created from this template.
	Metadata *ClusterObjectSetTemplateMetadataApplyConfiguration `json:"metadata,omitempty"`
	// spec defines the phases, objects, and configuration for each revision
	// created from this template.
	Spec *ClusterObjectSetTemplateSpecApplyConfiguration `json:"spec,omitempty"`
}

// ClusterObjectSetTemplateApplyConfiguration constructs a declarative configuration of the ClusterObjectSetTemplate type for use with
// apply.
func ClusterObjectSetTemplate() *ClusterObjectSetTemplateApplyConfiguration {
	return &ClusterObjectSetTemplateApplyConfiguration{}
}

// WithMetadata sets the Metadata field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Metadata field is set to the value of the last call.
func (b *ClusterObjectSetTemplateApplyConfiguration) WithMetadata(value *ClusterObjectSetTemplateMetadataApplyConfiguration) *ClusterObjectSetTemplateApplyConfiguration {
	b.Metadata = value
	return b
}

// WithSpec sets the Spec field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Spec field is set to the value of the last call.
func (b *ClusterObjectSetTemplateApplyConfiguration) WithSpec(value *ClusterObjectSetTemplateSpecApplyConfiguration) *ClusterObjectSetTemplateApplyConfiguration {
	b.Spec = value
	return b
}
