// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	apiv1alpha1 "github.com/joelanford/orb-operator/api/v1alpha1"
)

// ClusterObjectSetTemplateSpecApplyConfiguration represents a declarative configuration of the ClusterObjectSetTemplateSpec type for use
// with apply.
//
// ClusterObjectSetTemplateSpec defines the phases and collision protection
// settings that are embedded in each revision created from the template.
type ClusterObjectSetTemplateSpecApplyConfiguration struct {
	// collisionProtection sets the default collision protection for all phases
	// and objects in the revision. Individual phases and objects may override
	// this setting. When omitted, the platform chooses a reasonable default,
	// which is subject to change over time. The current default is "Prevent".
	// Allowed values are "Prevent", "IfNoController", and "None".
	CollisionProtection *apiv1alpha1.CollisionProtection `json:"collisionProtection,omitempty"`
	// phases is the ordered list of phases that define the managed objects. The
	// list must contain between 1 and 20 phases. Phases are applied
	// sequentially: the controller does not advance to the next phase until all
	// objects in the current phase satisfy their assertions.
	Phases []PhaseApplyConfiguration `json:"phases,omitempty"`
}

// ClusterObjectSetTemplateSpecApplyConfiguration constructs a declarative configuration of the ClusterObjectSetTemplateSpec type for use with
// apply.
func ClusterObjectSetTemplateSpec() *ClusterObjectSetTemplateSpecApplyConfiguration {
	return &ClusterObjectSetTemplateSpecApplyConfiguration{}
}

// WithCollisionProtection sets the CollisionProtection field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CollisionProtection field is set to the value of the last call.
func (b *ClusterObjectSetTemplateSpecApplyConfiguration) WithCollisionProtection(value apiv1alpha1.CollisionProtection) *ClusterObjectSetTemplateSpecApplyConfiguration {
	b.CollisionProtection = &value
	return b
}

// WithPhases adds the given value to the Phases field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Phases field.
func (b *ClusterObjectSetTemplateSpecApplyConfiguration) WithPhases(values ...*PhaseApplyConfiguration) *ClusterObjectSetTemplateSpecApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithPhases")
		}
		b.Phases = append(b.Phases, *values[i])
	}
	return b
}
