// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	v1 "k8s.io/client-go/applyconfigurations/meta/v1"
)

// ClusterObjectSetStatusApplyConfiguration represents a declarative configuration of the ClusterObjectSetStatus type for use
// with apply.
//
// ClusterObjectSetStatus reports the observed state of a
// ClusterObjectSet.
type ClusterObjectSetStatusApplyConfiguration struct {
	// conditions represent the latest available observations of the revision's
	// state. The "Available" condition indicates whether all managed objects in
	// this revision satisfy their assertions.
	Conditions []v1.ConditionApplyConfiguration `json:"conditions,omitempty"`
	// resolvedContentHash is a SHA-256 hash of all resolved phase object
	// content (inline objects and objectRef-resolved objects, in phase order).
	// Set once on the first successful resolution and never changed. Used to
	// detect content substitution (e.g. a ClusterObjectSlice deleted and
	// recreated with different content).
	ResolvedContentHash *string `json:"resolvedContentHash,omitempty"`
	// completedAt is the timestamp when all phases first completed
	// successfully. Set once and never cleared. Nil means the revision
	// has never been fully available. When set and Available is False,
	// the revision has regressed after a successful rollout.
	CompletedAt *metav1.Time `json:"completedAt,omitempty"`
	// objectCounts reports aggregate object counts across all phases.
	// Values are sums of the per-phase counts in observedPhases.
	ObjectCounts *ObjectCountsApplyConfiguration `json:"objectCounts,omitempty"`
	// observedPhases reports the observed state of each phase in the
	// revision. All phases from the spec are always listed, in spec
	// order. Each phase's status indicates whether the controller has
	// evaluated it and whether it has completed. The list may contain
	// at most 20 entries, matching the maximum number of spec phases.
	ObservedPhases []ObservedPhaseApplyConfiguration `json:"observedPhases,omitempty"`
}

// ClusterObjectSetStatusApplyConfiguration constructs a declarative configuration of the ClusterObjectSetStatus type for use with
// apply.
func ClusterObjectSetStatus() *ClusterObjectSetStatusApplyConfiguration {
	return &ClusterObjectSetStatusApplyConfiguration{}
}

// WithConditions adds the given value to the Conditions field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Conditions field.
func (b *ClusterObjectSetStatusApplyConfiguration) WithConditions(values ...*v1.ConditionApplyConfiguration) *ClusterObjectSetStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithConditions")
		}
		b.Conditions = append(b.Conditions, *values[i])
	}
	return b
}

// WithResolvedContentHash sets the ResolvedContentHash field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ResolvedContentHash field is set to the value of the last call.
func (b *ClusterObjectSetStatusApplyConfiguration) WithResolvedContentHash(value string) *ClusterObjectSetStatusApplyConfiguration {
	b.ResolvedContentHash = &value
	return b
}

// WithCompletedAt sets the CompletedAt field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CompletedAt field is set to the value of the last call.
func (b *ClusterObjectSetStatusApplyConfiguration) WithCompletedAt(value metav1.Time) *ClusterObjectSetStatusApplyConfiguration {
	b.CompletedAt = &value
	return b
}

// WithObjectCounts sets the ObjectCounts field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ObjectCounts field is set to the value of the last call.
func (b *ClusterObjectSetStatusApplyConfiguration) WithObjectCounts(value *ObjectCountsApplyConfiguration) *ClusterObjectSetStatusApplyConfiguration {
	b.ObjectCounts = value
	return b
}

// WithObservedPhases adds the given value to the ObservedPhases field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the ObservedPhases field.
func (b *ClusterObjectSetStatusApplyConfiguration) WithObservedPhases(values ...*ObservedPhaseApplyConfiguration) *ClusterObjectSetStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithObservedPhases")
		}
		b.ObservedPhases = append(b.ObservedPhases, *values[i])
	}
	return b
}
