// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

// ClusterObjectSetSpecApplyConfiguration represents a declarative configuration of the ClusterObjectSetSpec type for use
// with apply.
//
// ClusterObjectSetSpec defines the desired state of a ClusterObjectSet.
type ClusterObjectSetSpecApplyConfiguration struct {
	// revisionHistoryLimit is the maximum number of archived
	// ClusterObjectSetRevision resources to retain. Older archived revisions
	// beyond this limit are garbage collected by the controller. When omitted,
	// the platform chooses a reasonable default, which is subject to change over
	// time. The current default is 10. Set to 0 to disable revision history
	// entirely.
	RevisionHistoryLimit *int32 `json:"revisionHistoryLimit,omitempty"`
	// template defines the ClusterObjectSetRevision that the controller will
	// create whenever the template content changes.
	Template *ClusterObjectSetTemplateApplyConfiguration `json:"template,omitempty"`
}

// ClusterObjectSetSpecApplyConfiguration constructs a declarative configuration of the ClusterObjectSetSpec type for use with
// apply.
func ClusterObjectSetSpec() *ClusterObjectSetSpecApplyConfiguration {
	return &ClusterObjectSetSpecApplyConfiguration{}
}

// WithRevisionHistoryLimit sets the RevisionHistoryLimit field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RevisionHistoryLimit field is set to the value of the last call.
func (b *ClusterObjectSetSpecApplyConfiguration) WithRevisionHistoryLimit(value int32) *ClusterObjectSetSpecApplyConfiguration {
	b.RevisionHistoryLimit = &value
	return b
}

// WithTemplate sets the Template field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Template field is set to the value of the last call.
func (b *ClusterObjectSetSpecApplyConfiguration) WithTemplate(value *ClusterObjectSetTemplateApplyConfiguration) *ClusterObjectSetSpecApplyConfiguration {
	b.Template = value
	return b
}
