// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/client-go/applyconfigurations/meta/v1"
)

// ClusterObjectSetStatusApplyConfiguration represents a declarative configuration of the ClusterObjectSetStatus type for use
// with apply.
//
// ClusterObjectSetStatus reports the observed state of a ClusterObjectSet.
type ClusterObjectSetStatusApplyConfiguration struct {
	// conditions represent the latest available observations of the
	// ClusterObjectSet's state. The "Available" condition indicates whether the
	// active revision's managed objects satisfy their assertions.
	Conditions []v1.ConditionApplyConfiguration `json:"conditions,omitempty"`
	// activeRevisions holds the currently active (non-archived)
	// ClusterObjectSetRevision resources, including any revision just created
	// but not yet visible in the informer cache.
	ActiveRevisions []ClusterObjectSetRevisionStatusSummaryApplyConfiguration `json:"activeRevisions,omitempty"`
}

// ClusterObjectSetStatusApplyConfiguration constructs a declarative configuration of the ClusterObjectSetStatus type for use with
// apply.
func ClusterObjectSetStatus() *ClusterObjectSetStatusApplyConfiguration {
	return &ClusterObjectSetStatusApplyConfiguration{}
}

// WithConditions adds the given value to the Conditions field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Conditions field.
func (b *ClusterObjectSetStatusApplyConfiguration) WithConditions(values ...*v1.ConditionApplyConfiguration) *ClusterObjectSetStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithConditions")
		}
		b.Conditions = append(b.Conditions, *values[i])
	}
	return b
}

// WithActiveRevisions adds the given value to the ActiveRevisions field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the ActiveRevisions field.
func (b *ClusterObjectSetStatusApplyConfiguration) WithActiveRevisions(values ...*ClusterObjectSetRevisionStatusSummaryApplyConfiguration) *ClusterObjectSetStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithActiveRevisions")
		}
		b.ActiveRevisions = append(b.ActiveRevisions, *values[i])
	}
	return b
}
