// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/client-go/applyconfigurations/meta/v1"
)

// ClusterObjectSetRevisionStatusSummaryApplyConfiguration represents a declarative configuration of the ClusterObjectSetRevisionStatusSummary type for use
// with apply.
//
// ClusterObjectSetRevisionStatusSummary summarizes the state of a single active
// ClusterObjectSetRevision.
type ClusterObjectSetRevisionStatusSummaryApplyConfiguration struct {
	// name is the metadata.name of the ClusterObjectSetRevision resource.
	Name *string `json:"name,omitempty"`
	// conditions reflects the Available condition of the revision.
	Conditions []v1.ConditionApplyConfiguration `json:"conditions,omitempty"`
}

// ClusterObjectSetRevisionStatusSummaryApplyConfiguration constructs a declarative configuration of the ClusterObjectSetRevisionStatusSummary type for use with
// apply.
func ClusterObjectSetRevisionStatusSummary() *ClusterObjectSetRevisionStatusSummaryApplyConfiguration {
	return &ClusterObjectSetRevisionStatusSummaryApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *ClusterObjectSetRevisionStatusSummaryApplyConfiguration) WithName(value string) *ClusterObjectSetRevisionStatusSummaryApplyConfiguration {
	b.Name = &value
	return b
}

// WithConditions adds the given value to the Conditions field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Conditions field.
func (b *ClusterObjectSetRevisionStatusSummaryApplyConfiguration) WithConditions(values ...*v1.ConditionApplyConfiguration) *ClusterObjectSetRevisionStatusSummaryApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithConditions")
		}
		b.Conditions = append(b.Conditions, *values[i])
	}
	return b
}
