// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

// ClusterObjectDeploymentTemplateMetadataApplyConfiguration represents a declarative configuration of the ClusterObjectDeploymentTemplateMetadata type for use
// with apply.
//
// ClusterObjectDeploymentTemplateMetadata contains labels and annotations propagated
// to revisions created from the template. Labels and annotations must conform
// to the standard Kubernetes metadata format. Annotation values are bounded to
// 256 KiB each.
type ClusterObjectDeploymentTemplateMetadataApplyConfiguration struct {
	// labels is a set of key/value pairs propagated to each revision's metadata.
	// Keys and values must conform to the Kubernetes label format. A maximum of
	// 32 labels may be specified.
	Labels map[string]string `json:"labels,omitempty"`
	// annotations is a set of key/value pairs propagated to each revision's
	// metadata. Keys must conform to the Kubernetes annotation key format.
	// Values are free-form strings up to 256 KiB each. A maximum of 32
	// annotations may be specified.
	Annotations map[string]string `json:"annotations,omitempty"`
}

// ClusterObjectDeploymentTemplateMetadataApplyConfiguration constructs a declarative configuration of the ClusterObjectDeploymentTemplateMetadata type for use with
// apply.
func ClusterObjectDeploymentTemplateMetadata() *ClusterObjectDeploymentTemplateMetadataApplyConfiguration {
	return &ClusterObjectDeploymentTemplateMetadataApplyConfiguration{}
}

// WithLabels puts the entries into the Labels field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the Labels field,
// overwriting an existing map entries in Labels field with the same key.
func (b *ClusterObjectDeploymentTemplateMetadataApplyConfiguration) WithLabels(entries map[string]string) *ClusterObjectDeploymentTemplateMetadataApplyConfiguration {
	if b.Labels == nil && len(entries) > 0 {
		b.Labels = make(map[string]string, len(entries))
	}
	for k, v := range entries {
		b.Labels[k] = v
	}
	return b
}

// WithAnnotations puts the entries into the Annotations field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the Annotations field,
// overwriting an existing map entries in Annotations field with the same key.
func (b *ClusterObjectDeploymentTemplateMetadataApplyConfiguration) WithAnnotations(entries map[string]string) *ClusterObjectDeploymentTemplateMetadataApplyConfiguration {
	if b.Annotations == nil && len(entries) > 0 {
		b.Annotations = make(map[string]string, len(entries))
	}
	for k, v := range entries {
		b.Annotations[k] = v
	}
	return b
}
