// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

// ClusterObjectDeploymentTemplateApplyConfiguration represents a declarative configuration of the ClusterObjectDeploymentTemplate type for use
// with apply.
//
// ClusterObjectDeploymentTemplate defines the template used to stamp out
// ClusterObjectSet resources.
type ClusterObjectDeploymentTemplateApplyConfiguration struct {
	// metadata contains labels and annotations that are propagated to each
	// ClusterObjectSet created from this template.
	Metadata *ClusterObjectDeploymentTemplateMetadataApplyConfiguration `json:"metadata,omitempty"`
	// spec defines the phases, objects, and configuration for each revision
	// created from this template.
	Spec *ClusterObjectDeploymentTemplateSpecApplyConfiguration `json:"spec,omitempty"`
}

// ClusterObjectDeploymentTemplateApplyConfiguration constructs a declarative configuration of the ClusterObjectDeploymentTemplate type for use with
// apply.
func ClusterObjectDeploymentTemplate() *ClusterObjectDeploymentTemplateApplyConfiguration {
	return &ClusterObjectDeploymentTemplateApplyConfiguration{}
}

// WithMetadata sets the Metadata field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Metadata field is set to the value of the last call.
func (b *ClusterObjectDeploymentTemplateApplyConfiguration) WithMetadata(value *ClusterObjectDeploymentTemplateMetadataApplyConfiguration) *ClusterObjectDeploymentTemplateApplyConfiguration {
	b.Metadata = value
	return b
}

// WithSpec sets the Spec field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Spec field is set to the value of the last call.
func (b *ClusterObjectDeploymentTemplateApplyConfiguration) WithSpec(value *ClusterObjectDeploymentTemplateSpecApplyConfiguration) *ClusterObjectDeploymentTemplateApplyConfiguration {
	b.Spec = value
	return b
}
