// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

// ConditionEqualAssertionApplyConfiguration represents a declarative configuration of the ConditionEqualAssertion type for use
// with apply.
//
// ConditionEqualAssertion asserts that the object has a status condition
// matching the specified type and status value.
type ConditionEqualAssertionApplyConfiguration struct {
	// type is the condition type to match, for example "Available" or "Ready".
	Type *string `json:"type,omitempty"`
	// status is the expected value of the condition's status field. Allowed
	// values are "True", "False", and "Unknown".
	Status *string `json:"status,omitempty"`
}

// ConditionEqualAssertionApplyConfiguration constructs a declarative configuration of the ConditionEqualAssertion type for use with
// apply.
func ConditionEqualAssertion() *ConditionEqualAssertionApplyConfiguration {
	return &ConditionEqualAssertionApplyConfiguration{}
}

// WithType sets the Type field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Type field is set to the value of the last call.
func (b *ConditionEqualAssertionApplyConfiguration) WithType(value string) *ConditionEqualAssertionApplyConfiguration {
	b.Type = &value
	return b
}

// WithStatus sets the Status field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Status field is set to the value of the last call.
func (b *ConditionEqualAssertionApplyConfiguration) WithStatus(value string) *ConditionEqualAssertionApplyConfiguration {
	b.Status = &value
	return b
}
