// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

// FieldsEqualAssertionApplyConfiguration represents a declarative configuration of the FieldsEqualAssertion type for use
// with apply.
//
// FieldsEqualAssertion asserts that two fields on the object have equal values.
// Both fields are specified as JSON path expressions.
type FieldsEqualAssertionApplyConfiguration struct {
	// fieldA is the JSON path to the first field to compare.
	FieldA *string `json:"fieldA,omitempty"`
	// fieldB is the JSON path to the second field to compare.
	FieldB *string `json:"fieldB,omitempty"`
}

// FieldsEqualAssertionApplyConfiguration constructs a declarative configuration of the FieldsEqualAssertion type for use with
// apply.
func FieldsEqualAssertion() *FieldsEqualAssertionApplyConfiguration {
	return &FieldsEqualAssertionApplyConfiguration{}
}

// WithFieldA sets the FieldA field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the FieldA field is set to the value of the last call.
func (b *FieldsEqualAssertionApplyConfiguration) WithFieldA(value string) *FieldsEqualAssertionApplyConfiguration {
	b.FieldA = &value
	return b
}

// WithFieldB sets the FieldB field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the FieldB field is set to the value of the last call.
func (b *FieldsEqualAssertionApplyConfiguration) WithFieldB(value string) *FieldsEqualAssertionApplyConfiguration {
	b.FieldB = &value
	return b
}
