// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

// FieldValueAssertionApplyConfiguration represents a declarative configuration of the FieldValueAssertion type for use
// with apply.
//
// FieldValueAssertion asserts that a single field on the object matches an
// expected value.
type FieldValueAssertionApplyConfiguration struct {
	// fieldPath is the JSON path to the field to check.
	FieldPath *string `json:"fieldPath,omitempty"`
	// value is the expected value of the field. An empty string is a valid
	// expected value.
	Value *string `json:"value,omitempty"`
}

// FieldValueAssertionApplyConfiguration constructs a declarative configuration of the FieldValueAssertion type for use with
// apply.
func FieldValueAssertion() *FieldValueAssertionApplyConfiguration {
	return &FieldValueAssertionApplyConfiguration{}
}

// WithFieldPath sets the FieldPath field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the FieldPath field is set to the value of the last call.
func (b *FieldValueAssertionApplyConfiguration) WithFieldPath(value string) *FieldValueAssertionApplyConfiguration {
	b.FieldPath = &value
	return b
}

// WithValue sets the Value field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Value field is set to the value of the last call.
func (b *FieldValueAssertionApplyConfiguration) WithValue(value string) *FieldValueAssertionApplyConfiguration {
	b.Value = &value
	return b
}
