// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

// ObjectRefApplyConfiguration represents a declarative configuration of the ObjectRef type for use
// with apply.
//
// ObjectRef identifies a single object within a ClusterObjectSlice by its
// natural Kubernetes identity. The embedded ObjectKey fields (apiVersion,
// kind, name, namespace) must match a SliceObject entry in the named slice.
type ObjectRefApplyConfiguration struct {
	// sliceName is the metadata.name of the ClusterObjectSlice resource
	// containing the referenced object.
	SliceName                   *string `json:"sliceName,omitempty"`
	ObjectKeyApplyConfiguration `json:",inline"`
}

// ObjectRefApplyConfiguration constructs a declarative configuration of the ObjectRef type for use with
// apply.
func ObjectRef() *ObjectRefApplyConfiguration {
	return &ObjectRefApplyConfiguration{}
}

// WithSliceName sets the SliceName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SliceName field is set to the value of the last call.
func (b *ObjectRefApplyConfiguration) WithSliceName(value string) *ObjectRefApplyConfiguration {
	b.SliceName = &value
	return b
}

// WithAPIVersion sets the APIVersion field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the APIVersion field is set to the value of the last call.
func (b *ObjectRefApplyConfiguration) WithAPIVersion(value string) *ObjectRefApplyConfiguration {
	b.ObjectKeyApplyConfiguration.APIVersion = &value
	return b
}

// WithKind sets the Kind field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Kind field is set to the value of the last call.
func (b *ObjectRefApplyConfiguration) WithKind(value string) *ObjectRefApplyConfiguration {
	b.ObjectKeyApplyConfiguration.Kind = &value
	return b
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *ObjectRefApplyConfiguration) WithName(value string) *ObjectRefApplyConfiguration {
	b.ObjectKeyApplyConfiguration.Name = &value
	return b
}

// WithNamespace sets the Namespace field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Namespace field is set to the value of the last call.
func (b *ObjectRefApplyConfiguration) WithNamespace(value string) *ObjectRefApplyConfiguration {
	b.ObjectKeyApplyConfiguration.Namespace = &value
	return b
}
