// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

// ObjectStatusApplyConfiguration represents a declarative configuration of the ObjectStatus type for use
// with apply.
//
// ObjectStatus identifies a managed object and its failure messages.
type ObjectStatusApplyConfiguration struct {
	// group is the API group of the object (empty string for core
	// resources). At most 253 characters (DNS subdomain max).
	Group *string `json:"group,omitempty"`
	// version is the API version of the object. Must be between 1 and
	// 63 characters.
	Version *string `json:"version,omitempty"`
	// kind is the kind of the object. Must be between 1 and 63
	// characters.
	Kind *string `json:"kind,omitempty"`
	// namespace is the namespace of the object. Empty for cluster-scoped
	// resources. At most 253 characters (DNS subdomain max).
	Namespace *string `json:"namespace,omitempty"`
	// name is the name of the object. Must be between 1 and 253
	// characters (DNS subdomain max).
	Name *string `json:"name,omitempty"`
	// messages lists the failure reasons for this object. The maximum
	// of 17 entries accounts for up to 16 assertion probe failures
	// plus one collision message. Each message is at most 1024
	// characters; longer messages are truncated by the controller.
	Messages []string `json:"messages,omitempty"`
}

// ObjectStatusApplyConfiguration constructs a declarative configuration of the ObjectStatus type for use with
// apply.
func ObjectStatus() *ObjectStatusApplyConfiguration {
	return &ObjectStatusApplyConfiguration{}
}

// WithGroup sets the Group field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Group field is set to the value of the last call.
func (b *ObjectStatusApplyConfiguration) WithGroup(value string) *ObjectStatusApplyConfiguration {
	b.Group = &value
	return b
}

// WithVersion sets the Version field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Version field is set to the value of the last call.
func (b *ObjectStatusApplyConfiguration) WithVersion(value string) *ObjectStatusApplyConfiguration {
	b.Version = &value
	return b
}

// WithKind sets the Kind field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Kind field is set to the value of the last call.
func (b *ObjectStatusApplyConfiguration) WithKind(value string) *ObjectStatusApplyConfiguration {
	b.Kind = &value
	return b
}

// WithNamespace sets the Namespace field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Namespace field is set to the value of the last call.
func (b *ObjectStatusApplyConfiguration) WithNamespace(value string) *ObjectStatusApplyConfiguration {
	b.Namespace = &value
	return b
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *ObjectStatusApplyConfiguration) WithName(value string) *ObjectStatusApplyConfiguration {
	b.Name = &value
	return b
}

// WithMessages adds the given value to the Messages field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Messages field.
func (b *ObjectStatusApplyConfiguration) WithMessages(values ...string) *ObjectStatusApplyConfiguration {
	for i := range values {
		b.Messages = append(b.Messages, values[i])
	}
	return b
}
