// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

// ObjectCountsApplyConfiguration represents a declarative configuration of the ObjectCounts type for use
// with apply.
//
// ObjectCounts reports the number of objects in a phase by state.
type ObjectCountsApplyConfiguration struct {
	// total is the number of objects in this phase.
	Total *int64 `json:"total,omitempty"`
	// present is the number of objects in this phase that exist on the
	// cluster. During reconcile, this counts objects that the controller
	// has found or created. During teardown, this decrements toward zero
	// as objects are deleted.
	Present *int64 `json:"present,omitempty"`
	// synced is the number of objects in this phase whose cluster state
	// matches the desired state.
	Synced *int64 `json:"synced,omitempty"`
	// available is the number of objects in this phase that are synced
	// and pass their assertions.
	Available *int64 `json:"available,omitempty"`
}

// ObjectCountsApplyConfiguration constructs a declarative configuration of the ObjectCounts type for use with
// apply.
func ObjectCounts() *ObjectCountsApplyConfiguration {
	return &ObjectCountsApplyConfiguration{}
}

// WithTotal sets the Total field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Total field is set to the value of the last call.
func (b *ObjectCountsApplyConfiguration) WithTotal(value int64) *ObjectCountsApplyConfiguration {
	b.Total = &value
	return b
}

// WithPresent sets the Present field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Present field is set to the value of the last call.
func (b *ObjectCountsApplyConfiguration) WithPresent(value int64) *ObjectCountsApplyConfiguration {
	b.Present = &value
	return b
}

// WithSynced sets the Synced field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Synced field is set to the value of the last call.
func (b *ObjectCountsApplyConfiguration) WithSynced(value int64) *ObjectCountsApplyConfiguration {
	b.Synced = &value
	return b
}

// WithAvailable sets the Available field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Available field is set to the value of the last call.
func (b *ObjectCountsApplyConfiguration) WithAvailable(value int64) *ObjectCountsApplyConfiguration {
	b.Available = &value
	return b
}
