// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

// ObjectKeyApplyConfiguration represents a declarative configuration of the ObjectKey type for use
// with apply.
//
// ObjectKey uniquely identifies a Kubernetes object by its API identity.
// It is embedded inline in SliceObject and ObjectRef to provide a single
// source of truth for identity fields and their validation.
type ObjectKeyApplyConfiguration struct {
	// apiVersion is the API version of the object (e.g. "v1",
	// "apps/v1", "apiextensions.k8s.io/v1"). The format is an optional
	// DNS-1123 subdomain group followed by "/" and a DNS-1035 version.
	APIVersion *string `json:"apiVersion,omitempty"`
	// kind is the kind of the object (e.g. "ConfigMap", "Deployment").
	// Must be a DNS-1035 label with mixed case allowed.
	Kind *string `json:"kind,omitempty"`
	// name is the metadata.name of the object. Must be a valid DNS-1123
	// subdomain (lowercase alphanumeric, '-', or '.').
	Name *string `json:"name,omitempty"`
	// namespace is the metadata.namespace of the object. Defaults to empty
	// string for cluster-scoped resources. Must be a valid DNS-1123 label
	// when non-empty.
	Namespace *string `json:"namespace,omitempty"`
}

// ObjectKeyApplyConfiguration constructs a declarative configuration of the ObjectKey type for use with
// apply.
func ObjectKey() *ObjectKeyApplyConfiguration {
	return &ObjectKeyApplyConfiguration{}
}

// WithAPIVersion sets the APIVersion field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the APIVersion field is set to the value of the last call.
func (b *ObjectKeyApplyConfiguration) WithAPIVersion(value string) *ObjectKeyApplyConfiguration {
	b.APIVersion = &value
	return b
}

// WithKind sets the Kind field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Kind field is set to the value of the last call.
func (b *ObjectKeyApplyConfiguration) WithKind(value string) *ObjectKeyApplyConfiguration {
	b.Kind = &value
	return b
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *ObjectKeyApplyConfiguration) WithName(value string) *ObjectKeyApplyConfiguration {
	b.Name = &value
	return b
}

// WithNamespace sets the Namespace field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Namespace field is set to the value of the last call.
func (b *ObjectKeyApplyConfiguration) WithNamespace(value string) *ObjectKeyApplyConfiguration {
	b.Namespace = &value
	return b
}
