// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	apiv1alpha1 "github.com/joelanford/orb-operator/api/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// ObservedPhaseApplyConfiguration represents a declarative configuration of the ObservedPhase type for use
// with apply.
//
// ObservedPhase reports the observed state of a single phase in the rollout.
type ObservedPhaseApplyConfiguration struct {
	// name is the name of the phase from the spec. Must be a valid DNS-1035
	// label: lowercase alphanumeric characters or '-', must start with a
	// letter and end with an alphanumeric character (e.g. "my-phase",
	// "phase1"), matching the Phase name constraints.
	Name *string `json:"name,omitempty"`
	// status is the current state of this phase in the rollout. Must be
	// one of Invalid, Pending, Reconciling, WaitingForAssertions,
	// Available, Unknown, Superseded, TearingDown, or TeardownComplete.
	Status *apiv1alpha1.PhaseStatus `json:"status,omitempty"`
	// completedAt is the timestamp when this phase first became Available.
	// Set once and never cleared. Nil means the phase has never been
	// Available.
	CompletedAt *v1.Time `json:"completedAt,omitempty"`
	// message is a phase-level message providing context about the
	// current status (e.g. a validation error for Invalid phases, or
	// a summary for Pending phases). At most 1024 characters; longer
	// messages are truncated by the controller.
	Message *string `json:"message,omitempty"`
	// objectCounts reports the number of objects in this phase by state.
	ObjectCounts *ObjectCountsApplyConfiguration `json:"objectCounts,omitempty"`
	// objectDetails lists objects in this phase that are not yet
	// complete. For Reconciling and Pending phases, this includes probe
	// failures, collisions, creation/update errors, and any other
	// condition preventing completion. For TearingDown phases, this
	// lists objects still awaiting deletion. Each entry identifies the
	// object and carries failure messages. Empty when status is
	// Available, TeardownComplete, or Unknown. The list may contain at
	// most 50 entries, matching the maximum number of objects per phase.
	ObjectDetails []ObjectStatusApplyConfiguration `json:"objectDetails,omitempty"`
}

// ObservedPhaseApplyConfiguration constructs a declarative configuration of the ObservedPhase type for use with
// apply.
func ObservedPhase() *ObservedPhaseApplyConfiguration {
	return &ObservedPhaseApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *ObservedPhaseApplyConfiguration) WithName(value string) *ObservedPhaseApplyConfiguration {
	b.Name = &value
	return b
}

// WithStatus sets the Status field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Status field is set to the value of the last call.
func (b *ObservedPhaseApplyConfiguration) WithStatus(value apiv1alpha1.PhaseStatus) *ObservedPhaseApplyConfiguration {
	b.Status = &value
	return b
}

// WithCompletedAt sets the CompletedAt field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CompletedAt field is set to the value of the last call.
func (b *ObservedPhaseApplyConfiguration) WithCompletedAt(value v1.Time) *ObservedPhaseApplyConfiguration {
	b.CompletedAt = &value
	return b
}

// WithMessage sets the Message field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Message field is set to the value of the last call.
func (b *ObservedPhaseApplyConfiguration) WithMessage(value string) *ObservedPhaseApplyConfiguration {
	b.Message = &value
	return b
}

// WithObjectCounts sets the ObjectCounts field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ObjectCounts field is set to the value of the last call.
func (b *ObservedPhaseApplyConfiguration) WithObjectCounts(value *ObjectCountsApplyConfiguration) *ObservedPhaseApplyConfiguration {
	b.ObjectCounts = value
	return b
}

// WithObjectDetails adds the given value to the ObjectDetails field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the ObjectDetails field.
func (b *ObservedPhaseApplyConfiguration) WithObjectDetails(values ...*ObjectStatusApplyConfiguration) *ObservedPhaseApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithObjectDetails")
		}
		b.ObjectDetails = append(b.ObjectDetails, *values[i])
	}
	return b
}
