// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	apiv1alpha1 "github.com/joelanford/orb-operator/api/v1alpha1"
)

// ObservedPhaseApplyConfiguration represents a declarative configuration of the ObservedPhase type for use
// with apply.
//
// ObservedPhase reports the observed state of a single phase in the rollout.
type ObservedPhaseApplyConfiguration struct {
	// name is the name of the phase from the spec. Must be a valid DNS-1035
	// label: lowercase alphanumeric characters or '-', must start with a
	// letter and end with an alphanumeric character (e.g. "my-phase",
	// "phase1"), matching the Phase name constraints.
	Name *string `json:"name,omitempty"`
	// status is the current state of this phase in the rollout. Must be
	// one of Reconciling, Available, Unknown, Superseded, TearingDown, or
	// TeardownComplete.
	Status *apiv1alpha1.PhaseStatus `json:"status,omitempty"`
	// error is a phase-level error message describing a validation or
	// configuration problem with the phase itself (as opposed to
	// individual objects). At most 1024 characters; longer messages
	// are truncated by the controller.
	Error *string `json:"error,omitempty"`
	// incompleteObjects lists objects in this phase that are not
	// yet complete. For Reconciling phases, this includes probe
	// failures, collisions, creation/update errors, and any other
	// condition preventing completion. For TearingDown phases,
	// this lists objects still awaiting deletion. Each entry
	// identifies the object and carries failure messages. Empty
	// when status is Available, TeardownComplete, or Unknown.
	// The list may contain at most 50 entries, matching the maximum
	// number of objects per phase.
	IncompleteObjects []ObjectStatusApplyConfiguration `json:"incompleteObjects,omitempty"`
}

// ObservedPhaseApplyConfiguration constructs a declarative configuration of the ObservedPhase type for use with
// apply.
func ObservedPhase() *ObservedPhaseApplyConfiguration {
	return &ObservedPhaseApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *ObservedPhaseApplyConfiguration) WithName(value string) *ObservedPhaseApplyConfiguration {
	b.Name = &value
	return b
}

// WithStatus sets the Status field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Status field is set to the value of the last call.
func (b *ObservedPhaseApplyConfiguration) WithStatus(value apiv1alpha1.PhaseStatus) *ObservedPhaseApplyConfiguration {
	b.Status = &value
	return b
}

// WithError sets the Error field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Error field is set to the value of the last call.
func (b *ObservedPhaseApplyConfiguration) WithError(value string) *ObservedPhaseApplyConfiguration {
	b.Error = &value
	return b
}

// WithIncompleteObjects adds the given value to the IncompleteObjects field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the IncompleteObjects field.
func (b *ObservedPhaseApplyConfiguration) WithIncompleteObjects(values ...*ObjectStatusApplyConfiguration) *ObservedPhaseApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithIncompleteObjects")
		}
		b.IncompleteObjects = append(b.IncompleteObjects, *values[i])
	}
	return b
}
