// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	apiv1alpha1 "github.com/joelanford/orb-operator/api/v1alpha1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// PhaseObjectApplyConfiguration represents a declarative configuration of the PhaseObject type for use
// with apply.
//
// PhaseObject wraps a single Kubernetes object with optional collision
// protection and availability assertions. The object is specified either
// inline (via object) or by reference to a ClusterObjectSlice entry (via
// objectRef). Exactly one must be set.
type PhaseObjectApplyConfiguration struct {
	// object is the inline Kubernetes resource manifest to create or update.
	// The controller applies this object to the cluster and manages it for
	// the lifetime of the owning revision. Mutually exclusive with objectRef.
	Object *runtime.RawExtension `json:"object,omitempty"`
	// objectRef identifies a Kubernetes object stored in a ClusterObjectSlice.
	// The COS controller resolves the reference at reconcile time by looking
	// up the named slice and matching the object by its identity fields.
	// Mutually exclusive with object.
	ObjectRef *ObjectRefApplyConfiguration `json:"objectRef,omitempty"`
	// collisionProtection overrides the phase-level collision protection
	// setting for this specific object. When omitted, the phase-level setting
	// applies. This field applies identically whether the object is inline
	// or referenced via objectRef.
	CollisionProtection *apiv1alpha1.CollisionProtection `json:"collisionProtection,omitempty"`
	// assertions define conditions that must be met before this object is
	// considered available. A maximum of 16 assertions may be specified. When
	// omitted, the object is considered available immediately after successful
	// apply. This field applies identically whether the object is inline or
	// referenced via objectRef.
	Assertions []AssertionApplyConfiguration `json:"assertions,omitempty"`
}

// PhaseObjectApplyConfiguration constructs a declarative configuration of the PhaseObject type for use with
// apply.
func PhaseObject() *PhaseObjectApplyConfiguration {
	return &PhaseObjectApplyConfiguration{}
}

// WithObject sets the Object field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Object field is set to the value of the last call.
func (b *PhaseObjectApplyConfiguration) WithObject(value runtime.RawExtension) *PhaseObjectApplyConfiguration {
	b.Object = &value
	return b
}

// WithObjectRef sets the ObjectRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ObjectRef field is set to the value of the last call.
func (b *PhaseObjectApplyConfiguration) WithObjectRef(value *ObjectRefApplyConfiguration) *PhaseObjectApplyConfiguration {
	b.ObjectRef = value
	return b
}

// WithCollisionProtection sets the CollisionProtection field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CollisionProtection field is set to the value of the last call.
func (b *PhaseObjectApplyConfiguration) WithCollisionProtection(value apiv1alpha1.CollisionProtection) *PhaseObjectApplyConfiguration {
	b.CollisionProtection = &value
	return b
}

// WithAssertions adds the given value to the Assertions field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Assertions field.
func (b *PhaseObjectApplyConfiguration) WithAssertions(values ...*AssertionApplyConfiguration) *PhaseObjectApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithAssertions")
		}
		b.Assertions = append(b.Assertions, *values[i])
	}
	return b
}
