// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	apiv1alpha1 "github.com/joelanford/orb-operator/api/v1alpha1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// PhaseObjectApplyConfiguration represents a declarative configuration of the PhaseObject type for use
// with apply.
//
// PhaseObject wraps a single Kubernetes object with optional collision
// protection and availability assertions.
type PhaseObjectApplyConfiguration struct {
	// object is the Kubernetes resource to create or update. The controller
	// applies this object to the cluster and manages it for the lifetime of the
	// owning revision.
	Object *runtime.RawExtension `json:"object,omitempty"`
	// collisionProtection overrides the phase-level collision protection
	// setting for this specific object. When omitted, the phase-level setting
	// applies.
	CollisionProtection *apiv1alpha1.CollisionProtection `json:"collisionProtection,omitempty"`
	// assertions define conditions that must be met before this object is
	// considered available. A maximum of 16 assertions may be specified. When
	// omitted, the object is considered available immediately after successful
	// apply.
	Assertions []AssertionApplyConfiguration `json:"assertions,omitempty"`
}

// PhaseObjectApplyConfiguration constructs a declarative configuration of the PhaseObject type for use with
// apply.
func PhaseObject() *PhaseObjectApplyConfiguration {
	return &PhaseObjectApplyConfiguration{}
}

// WithObject sets the Object field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Object field is set to the value of the last call.
func (b *PhaseObjectApplyConfiguration) WithObject(value runtime.RawExtension) *PhaseObjectApplyConfiguration {
	b.Object = &value
	return b
}

// WithCollisionProtection sets the CollisionProtection field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CollisionProtection field is set to the value of the last call.
func (b *PhaseObjectApplyConfiguration) WithCollisionProtection(value apiv1alpha1.CollisionProtection) *PhaseObjectApplyConfiguration {
	b.CollisionProtection = &value
	return b
}

// WithAssertions adds the given value to the Assertions field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Assertions field.
func (b *PhaseObjectApplyConfiguration) WithAssertions(values ...*AssertionApplyConfiguration) *PhaseObjectApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithAssertions")
		}
		b.Assertions = append(b.Assertions, *values[i])
	}
	return b
}
