// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	apiv1alpha1 "github.com/joelanford/orb-operator/api/v1alpha1"
)

// PhaseApplyConfiguration represents a declarative configuration of the Phase type for use
// with apply.
//
// Phase is an ordered group of objects that are applied together. Phases within
// a revision are applied sequentially: the controller does not advance to the
// next phase until all objects in the current phase satisfy their assertions.
type PhaseApplyConfiguration struct {
	// name is a human-readable identifier for this phase. It is used in log
	// messages and status reporting. Must be a valid DNS-1035 label: lowercase
	// alphanumeric characters or '-', must start with a letter and end with
	// an alphanumeric character (e.g. "my-phase", "phase1").
	Name *string `json:"name,omitempty"`
	// collisionProtection overrides the revision-level collision protection
	// setting for all objects in this phase. When omitted, the revision-level
	// setting applies.
	CollisionProtection *apiv1alpha1.CollisionProtection `json:"collisionProtection,omitempty"`
	// objects is the list of Kubernetes objects to manage in this phase. The
	// list must contain between 1 and 50 objects.
	Objects []PhaseObjectApplyConfiguration `json:"objects,omitempty"`
}

// PhaseApplyConfiguration constructs a declarative configuration of the Phase type for use with
// apply.
func Phase() *PhaseApplyConfiguration {
	return &PhaseApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *PhaseApplyConfiguration) WithName(value string) *PhaseApplyConfiguration {
	b.Name = &value
	return b
}

// WithCollisionProtection sets the CollisionProtection field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CollisionProtection field is set to the value of the last call.
func (b *PhaseApplyConfiguration) WithCollisionProtection(value apiv1alpha1.CollisionProtection) *PhaseApplyConfiguration {
	b.CollisionProtection = &value
	return b
}

// WithObjects adds the given value to the Objects field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Objects field.
func (b *PhaseApplyConfiguration) WithObjects(values ...*PhaseObjectApplyConfiguration) *PhaseApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithObjects")
		}
		b.Objects = append(b.Objects, *values[i])
	}
	return b
}
