// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

// SliceObjectApplyConfiguration represents a declarative configuration of the SliceObject type for use
// with apply.
//
// SliceObject holds a single Kubernetes object manifest with explicit identity
// fields for keyed lookup and admission-time uniqueness validation.
type SliceObjectApplyConfiguration struct {
	ObjectKeyApplyConfiguration `json:",inline"`
	// content is the Kubernetes object manifest as raw JSON, or as
	// gzip-compressed JSON. The format is auto-detected by checking for
	// the gzip magic number (0x1f 0x8b) in the first two bytes.
	// Decompression happens lazily when the object is referenced by a
	// ClusterObjectSet. The []byte type is automatically base64-encoded
	// during JSON serialization by the Kubernetes API machinery — no
	// user-space encoding is needed.
	Content []byte `json:"content,omitempty"`
}

// SliceObjectApplyConfiguration constructs a declarative configuration of the SliceObject type for use with
// apply.
func SliceObject() *SliceObjectApplyConfiguration {
	return &SliceObjectApplyConfiguration{}
}

// WithAPIVersion sets the APIVersion field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the APIVersion field is set to the value of the last call.
func (b *SliceObjectApplyConfiguration) WithAPIVersion(value string) *SliceObjectApplyConfiguration {
	b.ObjectKeyApplyConfiguration.APIVersion = &value
	return b
}

// WithKind sets the Kind field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Kind field is set to the value of the last call.
func (b *SliceObjectApplyConfiguration) WithKind(value string) *SliceObjectApplyConfiguration {
	b.ObjectKeyApplyConfiguration.Kind = &value
	return b
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *SliceObjectApplyConfiguration) WithName(value string) *SliceObjectApplyConfiguration {
	b.ObjectKeyApplyConfiguration.Name = &value
	return b
}

// WithNamespace sets the Namespace field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Namespace field is set to the value of the last call.
func (b *SliceObjectApplyConfiguration) WithNamespace(value string) *SliceObjectApplyConfiguration {
	b.ObjectKeyApplyConfiguration.Namespace = &value
	return b
}

// WithContent adds the given value to the Content field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Content field.
func (b *SliceObjectApplyConfiguration) WithContent(values ...byte) *SliceObjectApplyConfiguration {
	for i := range values {
		b.Content = append(b.Content, values[i])
	}
	return b
}
