// Code generated by controller-gen. DO NOT EDIT.

package internal

import (
	fmt "fmt"
	sync "sync"

	typed "sigs.k8s.io/structured-merge-diff/v6/typed"
)

func Parser() *typed.Parser {
	parserOnce.Do(func() {
		var err error
		parser, err = typed.NewParser(schemaYAML)
		if err != nil {
			panic(fmt.Sprintf("Failed to parse schema: %v", err))
		}
	})
	return parser
}

var parserOnce sync.Once
var parser *typed.Parser
var schemaYAML = typed.YAMLObject(`types:
- name: com.github.joelanford.orb-operator.api.v1alpha1.Assertion
  map:
    fields:
    - name: celExpression
      type:
        namedType: com.github.joelanford.orb-operator.api.v1alpha1.CELExpressionAssertion
    - name: conditionEqual
      type:
        namedType: com.github.joelanford.orb-operator.api.v1alpha1.ConditionEqualAssertion
    - name: fieldValue
      type:
        namedType: com.github.joelanford.orb-operator.api.v1alpha1.FieldValueAssertion
    - name: fieldsEqual
      type:
        namedType: com.github.joelanford.orb-operator.api.v1alpha1.FieldsEqualAssertion
- name: com.github.joelanford.orb-operator.api.v1alpha1.CELExpressionAssertion
  map:
    fields:
    - name: expression
      type:
        scalar: string
    - name: message
      type:
        scalar: string
- name: com.github.joelanford.orb-operator.api.v1alpha1.ClusterObjectDeployment
  map:
    fields:
    - name: apiVersion
      type:
        scalar: string
    - name: kind
      type:
        scalar: string
    - name: metadata
      type:
        namedType: io.k8s.apimachinery.pkg.apis.meta.v1.ObjectMeta
    - name: spec
      type:
        namedType: com.github.joelanford.orb-operator.api.v1alpha1.ClusterObjectDeploymentSpec
    - name: status
      type:
        namedType: com.github.joelanford.orb-operator.api.v1alpha1.ClusterObjectDeploymentStatus
- name: com.github.joelanford.orb-operator.api.v1alpha1.ClusterObjectDeploymentSpec
  map:
    fields:
    - name: progressDeadlineMinutes
      type:
        scalar: numeric
    - name: revisionHistoryLimit
      type:
        scalar: numeric
    - name: template
      type:
        namedType: com.github.joelanford.orb-operator.api.v1alpha1.ClusterObjectDeploymentTemplate
- name: com.github.joelanford.orb-operator.api.v1alpha1.ClusterObjectDeploymentStatus
  map:
    fields:
    - name: activeRevisions
      type:
        list:
          elementType:
            namedType: com.github.joelanford.orb-operator.api.v1alpha1.ClusterObjectSetStatusSummary
          elementRelationship: associative
          keys:
          - name
    - name: conditions
      type:
        list:
          elementType:
            namedType: io.k8s.apimachinery.pkg.apis.meta.v1.Condition
          elementRelationship: associative
          keys:
          - type
    - name: objectCounts
      type:
        namedType: com.github.joelanford.orb-operator.api.v1alpha1.ObjectCounts
- name: com.github.joelanford.orb-operator.api.v1alpha1.ClusterObjectDeploymentTemplate
  map:
    fields:
    - name: metadata
      type:
        namedType: com.github.joelanford.orb-operator.api.v1alpha1.ClusterObjectDeploymentTemplateMetadata
    - name: spec
      type:
        namedType: com.github.joelanford.orb-operator.api.v1alpha1.ClusterObjectDeploymentTemplateSpec
- name: com.github.joelanford.orb-operator.api.v1alpha1.ClusterObjectDeploymentTemplateMetadata
  map:
    fields:
    - name: annotations
      type:
        map:
          elementType:
            scalar: string
    - name: labels
      type:
        map:
          elementType:
            scalar: string
- name: com.github.joelanford.orb-operator.api.v1alpha1.ClusterObjectDeploymentTemplateSpec
  map:
    fields:
    - name: collisionProtection
      type:
        namedType: com.github.joelanford.orb-operator.api.v1alpha1.CollisionProtection
    - name: phases
      type:
        list:
          elementType:
            namedType: com.github.joelanford.orb-operator.api.v1alpha1.Phase
          elementRelationship: atomic
- name: com.github.joelanford.orb-operator.api.v1alpha1.ClusterObjectSet
  map:
    fields:
    - name: apiVersion
      type:
        scalar: string
    - name: kind
      type:
        scalar: string
    - name: metadata
      type:
        namedType: io.k8s.apimachinery.pkg.apis.meta.v1.ObjectMeta
    - name: spec
      type:
        namedType: com.github.joelanford.orb-operator.api.v1alpha1.ClusterObjectSetSpec
    - name: status
      type:
        namedType: com.github.joelanford.orb-operator.api.v1alpha1.ClusterObjectSetStatus
- name: com.github.joelanford.orb-operator.api.v1alpha1.ClusterObjectSetSpec
  map:
    fields:
    - name: collisionProtection
      type:
        namedType: com.github.joelanford.orb-operator.api.v1alpha1.CollisionProtection
    - name: group
      type:
        scalar: string
    - name: lifecycleState
      type:
        namedType: com.github.joelanford.orb-operator.api.v1alpha1.LifecycleState
    - name: phases
      type:
        list:
          elementType:
            namedType: com.github.joelanford.orb-operator.api.v1alpha1.Phase
          elementRelationship: atomic
    - name: revision
      type:
        scalar: numeric
- name: com.github.joelanford.orb-operator.api.v1alpha1.ClusterObjectSetStatus
  map:
    fields:
    - name: completedAt
      type:
        namedType: io.k8s.apimachinery.pkg.apis.meta.v1.Time
    - name: conditions
      type:
        list:
          elementType:
            namedType: io.k8s.apimachinery.pkg.apis.meta.v1.Condition
          elementRelationship: associative
          keys:
          - type
    - name: objectCounts
      type:
        namedType: com.github.joelanford.orb-operator.api.v1alpha1.ObjectCounts
    - name: observedPhases
      type:
        list:
          elementType:
            namedType: com.github.joelanford.orb-operator.api.v1alpha1.ObservedPhase
          elementRelationship: associative
          keys:
          - name
    - name: resolvedContentHash
      type:
        scalar: string
- name: com.github.joelanford.orb-operator.api.v1alpha1.ClusterObjectSetStatusSummary
  map:
    fields:
    - name: conditions
      type:
        list:
          elementType:
            namedType: io.k8s.apimachinery.pkg.apis.meta.v1.Condition
          elementRelationship: associative
          keys:
          - type
    - name: name
      type:
        scalar: string
- name: com.github.joelanford.orb-operator.api.v1alpha1.ClusterObjectSlice
  map:
    fields:
    - name: apiVersion
      type:
        scalar: string
    - name: count
      type:
        scalar: numeric
    - name: kind
      type:
        scalar: string
    - name: metadata
      type:
        namedType: io.k8s.apimachinery.pkg.apis.meta.v1.ObjectMeta
    - name: objects
      type:
        list:
          elementType:
            namedType: com.github.joelanford.orb-operator.api.v1alpha1.SliceObject
          elementRelationship: associative
          keys:
          - apiVersion
          - kind
          - name
          - namespace
- name: com.github.joelanford.orb-operator.api.v1alpha1.CollisionProtection
  scalar: string
- name: com.github.joelanford.orb-operator.api.v1alpha1.ConditionEqualAssertion
  map:
    fields:
    - name: status
      type:
        scalar: string
    - name: type
      type:
        scalar: string
- name: com.github.joelanford.orb-operator.api.v1alpha1.FieldValueAssertion
  map:
    fields:
    - name: fieldPath
      type:
        scalar: string
    - name: value
      type:
        scalar: string
- name: com.github.joelanford.orb-operator.api.v1alpha1.FieldsEqualAssertion
  map:
    fields:
    - name: fieldA
      type:
        scalar: string
    - name: fieldB
      type:
        scalar: string
- name: com.github.joelanford.orb-operator.api.v1alpha1.LifecycleState
  scalar: string
- name: com.github.joelanford.orb-operator.api.v1alpha1.ObjectCounts
  map:
    fields:
    - name: available
      type:
        scalar: numeric
    - name: present
      type:
        scalar: numeric
    - name: synced
      type:
        scalar: numeric
    - name: total
      type:
        scalar: numeric
- name: com.github.joelanford.orb-operator.api.v1alpha1.ObjectRef
  map:
    fields:
    - name: apiVersion
      type:
        scalar: string
    - name: kind
      type:
        scalar: string
    - name: name
      type:
        scalar: string
    - name: namespace
      type:
        scalar: string
      default: ""
    - name: sliceName
      type:
        scalar: string
- name: com.github.joelanford.orb-operator.api.v1alpha1.ObjectStatus
  map:
    fields:
    - name: group
      type:
        scalar: string
    - name: kind
      type:
        scalar: string
    - name: messages
      type:
        list:
          elementType:
            scalar: string
          elementRelationship: atomic
    - name: name
      type:
        scalar: string
    - name: namespace
      type:
        scalar: string
    - name: version
      type:
        scalar: string
- name: com.github.joelanford.orb-operator.api.v1alpha1.ObservedPhase
  map:
    fields:
    - name: completedAt
      type:
        namedType: io.k8s.apimachinery.pkg.apis.meta.v1.Time
    - name: message
      type:
        scalar: string
    - name: name
      type:
        scalar: string
    - name: objectCounts
      type:
        namedType: com.github.joelanford.orb-operator.api.v1alpha1.ObjectCounts
    - name: objectDetails
      type:
        list:
          elementType:
            namedType: com.github.joelanford.orb-operator.api.v1alpha1.ObjectStatus
          elementRelationship: atomic
    - name: status
      type:
        namedType: com.github.joelanford.orb-operator.api.v1alpha1.PhaseStatus
- name: com.github.joelanford.orb-operator.api.v1alpha1.Phase
  map:
    fields:
    - name: collisionProtection
      type:
        namedType: com.github.joelanford.orb-operator.api.v1alpha1.CollisionProtection
    - name: name
      type:
        scalar: string
    - name: objects
      type:
        list:
          elementType:
            namedType: com.github.joelanford.orb-operator.api.v1alpha1.PhaseObject
          elementRelationship: atomic
- name: com.github.joelanford.orb-operator.api.v1alpha1.PhaseObject
  map:
    fields:
    - name: assertions
      type:
        list:
          elementType:
            namedType: com.github.joelanford.orb-operator.api.v1alpha1.Assertion
          elementRelationship: atomic
    - name: collisionProtection
      type:
        namedType: com.github.joelanford.orb-operator.api.v1alpha1.CollisionProtection
    - name: object
      type:
        namedType: __untyped_atomic_
    - name: objectRef
      type:
        namedType: com.github.joelanford.orb-operator.api.v1alpha1.ObjectRef
- name: com.github.joelanford.orb-operator.api.v1alpha1.PhaseStatus
  scalar: string
- name: com.github.joelanford.orb-operator.api.v1alpha1.SliceObject
  map:
    fields:
    - name: apiVersion
      type:
        scalar: string
    - name: content
      type:
        scalar: string
    - name: kind
      type:
        scalar: string
    - name: name
      type:
        scalar: string
    - name: namespace
      type:
        scalar: string
      default: ""
- name: io.k8s.apimachinery.pkg.apis.meta.v1.Condition
  map:
    fields:
    - name: lastTransitionTime
      type:
        namedType: io.k8s.apimachinery.pkg.apis.meta.v1.Time
    - name: message
      type:
        scalar: string
    - name: observedGeneration
      type:
        scalar: numeric
    - name: reason
      type:
        scalar: string
    - name: status
      type:
        namedType: io.k8s.apimachinery.pkg.apis.meta.v1.ConditionStatus
    - name: type
      type:
        scalar: string
- name: io.k8s.apimachinery.pkg.apis.meta.v1.ConditionStatus
  scalar: string
- name: io.k8s.apimachinery.pkg.apis.meta.v1.FieldsV1
  map:
    elementType:
      scalar: untyped
      list:
        elementType:
          namedType: __untyped_atomic_
        elementRelationship: atomic
      map:
        elementType:
          namedType: __untyped_deduced_
        elementRelationship: separable
- name: io.k8s.apimachinery.pkg.apis.meta.v1.ManagedFieldsEntry
  map:
    fields:
    - name: apiVersion
      type:
        scalar: string
    - name: fieldsType
      type:
        scalar: string
    - name: fieldsV1
      type:
        namedType: io.k8s.apimachinery.pkg.apis.meta.v1.FieldsV1
    - name: manager
      type:
        scalar: string
    - name: operation
      type:
        namedType: io.k8s.apimachinery.pkg.apis.meta.v1.ManagedFieldsOperationType
    - name: subresource
      type:
        scalar: string
    - name: time
      type:
        namedType: io.k8s.apimachinery.pkg.apis.meta.v1.Time
- name: io.k8s.apimachinery.pkg.apis.meta.v1.ManagedFieldsOperationType
  scalar: string
- name: io.k8s.apimachinery.pkg.apis.meta.v1.ObjectMeta
  map:
    fields:
    - name: annotations
      type:
        map:
          elementType:
            scalar: string
    - name: creationTimestamp
      type:
        namedType: io.k8s.apimachinery.pkg.apis.meta.v1.Time
    - name: deletionGracePeriodSeconds
      type:
        scalar: numeric
    - name: deletionTimestamp
      type:
        namedType: io.k8s.apimachinery.pkg.apis.meta.v1.Time
    - name: finalizers
      type:
        list:
          elementType:
            scalar: string
          elementRelationship: associative
    - name: generateName
      type:
        scalar: string
    - name: generation
      type:
        scalar: numeric
    - name: labels
      type:
        map:
          elementType:
            scalar: string
    - name: managedFields
      type:
        list:
          elementType:
            namedType: io.k8s.apimachinery.pkg.apis.meta.v1.ManagedFieldsEntry
          elementRelationship: atomic
    - name: name
      type:
        scalar: string
    - name: namespace
      type:
        scalar: string
    - name: ownerReferences
      type:
        list:
          elementType:
            namedType: io.k8s.apimachinery.pkg.apis.meta.v1.OwnerReference
          elementRelationship: associative
          keys:
          - uid
    - name: resourceVersion
      type:
        scalar: string
    - name: selfLink
      type:
        scalar: string
    - name: uid
      type:
        namedType: io.k8s.apimachinery.pkg.types.UID
- name: io.k8s.apimachinery.pkg.apis.meta.v1.OwnerReference
  map:
    fields:
    - name: apiVersion
      type:
        scalar: string
    - name: blockOwnerDeletion
      type:
        scalar: boolean
    - name: controller
      type:
        scalar: boolean
    - name: kind
      type:
        scalar: string
    - name: name
      type:
        scalar: string
    - name: uid
      type:
        namedType: io.k8s.apimachinery.pkg.types.UID
    elementRelationship: atomic
- name: io.k8s.apimachinery.pkg.apis.meta.v1.Time
  scalar: untyped
- name: io.k8s.apimachinery.pkg.runtime.RawExtension
  map:
    elementType:
      scalar: untyped
      list:
        elementType:
          namedType: __untyped_atomic_
        elementRelationship: atomic
      map:
        elementType:
          namedType: __untyped_deduced_
        elementRelationship: separable
- name: io.k8s.apimachinery.pkg.types.UID
  scalar: string
- name: __untyped_atomic_
  scalar: untyped
  list:
    elementType:
      namedType: __untyped_atomic_
    elementRelationship: atomic
  map:
    elementType:
      namedType: __untyped_atomic_
    elementRelationship: atomic
- name: __untyped_deduced_
  scalar: untyped
  list:
    elementType:
      namedType: __untyped_atomic_
    elementRelationship: atomic
  map:
    elementType:
      namedType: __untyped_deduced_
    elementRelationship: separable
`)
